version: '3.8'
services:
  eureka-server:
    image: eureka-server
    build:
      context: ./eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservices-network

  api-gateway:
    image: api-gateway
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - microservices-network

  product-service:
    image: product-service
    build:
      context: ./product-service
    ports:
      - "8081:8081"
    depends_on:
      - product-db
      - eureka-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://product-db:5432/week8_productdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=sapassword
    networks:
      - microservices-network

  order-service:
    image: order-service
    build:
      context: ./order-service
    ports:
      - "8082:8082"
    depends_on:
      - order-db
      - eureka-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://order-db:5432/week8_orderdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=sapassword
    networks:
      - microservices-network

  customer-service:
    image: customer-service
    build:
      context: ./customer-service
    ports:
      - "8084:8084"
    depends_on:
      - customer-db
      - eureka-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://customer-db:5432/week8_customerdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=sapassword
    networks:
      - microservices-network

  product-db:
    image: postgres:14
    environment:
      - POSTGRES_DB=week8_productdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sapassword
    ports:
      - "5433:5432"
    networks:
      - microservices-network

  order-db:
    image: postgres:14
    environment:
      - POSTGRES_DB=week8_orderdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sapassword
    ports:
      - "5434:5432"
    networks:
      - microservices-network

  customer-db:
    image: postgres:14
    environment:
      - POSTGRES_DB=week8_customerdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sapassword
    ports:
      - "5435:5432"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge